### PR TITLE
Fix some bugs and improvements 

### PR DESCRIPTION
**Pull request by mouhb**
Issues treated in this pull request :
1) XTOTEM-38 : Remove the use of the custom skin in the TotemCode space
2) XTOTEM-40 : Remove the use of iframes in the edit totem items section
4) XTOTEM-39 : Put the create new section form in a popup
5) XTOTEM-41 : Change the confirmation box when removing the background
6) XTOTEM-42 : Improve the display of action buttons on the totem UI
...

### CODE REVIEW

**Comment by Enygma2002** [comment]
Hi @mouhb. I am curious what are your expectations regarding this PR, in other words, what is the reason you did this PR the way you did it?

Same question for xwiki-contrib/displayer-multiselect-suggest#4, but let's focus on this PR first.

**Comment by mouhb** [comment]
Hi Eduard,
Normally I should make a PR for each commit.
But I completely forgot.

**Comment by Enygma2002** [comment]
Actually, it's a PR for each issue handled (since an issue can require more than 1 commit to fix it).

The problem with these 2 PRs (most the current one) is that they are non-reviewable. No dev can actually manage to review the code used to fix/handle 5-6 issues _at the same time_. Sure, you can review bits of code, but without context information (or context overload in this case), you can not asses if a code decision is good and what is the impact it will have on the rest of the application.

So, at their current state, the 2 PRs are unusable and need to be redone.

Also, make sure to create PRs only for the issues of which you are not sure of the solution you applied and for which you want a review. Since you have commit rights on contrib, you can directly commit the issues for which you are confident on the solution you applied and for which you don`t need a review. Make sure you use the PR system correctly (as a review tool and not as a contribution/commit tool).

And finally, always consider the person who is going to review your code, put yourself in their shoes and try not to put too many obstacles in the way of them looking at your code and understanding it. Otherwise, the chances of getting a review diminish when the complexity of the actual task of reviewing increases.

**Comment by mouhb** [comment]
Thank you for theses precious  advice Eduard. 
Effectively I am confident for the solution I have applied, but we always need an other point of view.
I will redo it.

**Comment by lucaa** [comment]
I have made a 1.4-SNAPSHOT build of the totem application with these fixes and I tested it on a 6.4.5: it does not make things much worse than before (at least what I tested) and it's improving things a little, at least the access to the totem sheets is better because this commit is removing the custom skin on the totem code space.
I am merging it, and we'll continue bugfixing from there.

**Pull request merged**
