### PR TITLE
Add the xwiki-labs logo to the README.md file

### PR DESCRIPTION
**Pull request by mouhb**

### CODE REVIEW

**Comment by cjdelisle** [comment]
What an excellent thing to add to the readme :D

**Comment by vmassol** [comment]
I'm not so sure. The goal of xwiki-contrib is to be a place to collaborate on projects. Even if these projects may have started as XWiki Labs projects, once they're given to xwiki-contrib they're a project belonging to all those who contribute to it even if they're not xwiki labs developers.

I'd have preferred some logo or message that mentioned that the code was initially created by the XWiki Labs team but that shows that it's no longer.

It would be similar to have a picture of ludovic on all pages of xwiki.org with the text "A Ludovic Project". Or a "XWiki SAS project". But that would be denying all the work done by the various committers thereafter. Saying that it was originally created by Ludovic or XWiki SAS is fine though.

WDYT?

**Comment by cjdelisle** [comment]
We can change it to "Donated by XWiki Labs"  (Vincent and I had a quick chat and decided that would be better)

**Comment by evalica** [comment]
Also, now you may called it XWiki Labs, but some projects you labeled as XWiki Labs, were developed in 2013, when XWiki labs didn't existed. 

Not sure what is the purpose of these readme updates.
- Does it means that the Totem Application is supported by XWiki Labs? Are you going to test it regularly against newer versions of XWiki?
- Does it means the developers that worked on this application were all part of XWiki Labs?
- Does it means only developers from XWiki Labs are 'allowed' to change code on this?

**Comment by Enygma2002** [comment]
I`m not sure this is right.

Are you sure this extension was initially developed by XWiki Labs so that it can be donated? My memory tells me otherwise. Github seems to agree:
- https://github.com/xwiki-contrib/totem-application/commit/f6f50977ffca7f7c5794c904c38a057b0bc236db
- https://github.com/xwiki-contrib/totem-application/commit/33c1d48405d2d3b3675db79311a430a17954fa88

Please be more careful with these kind of stamps (did not check the other affected repositories, since there were quite a few), but unless you are sure of what you are doing, you risk offending people out of ignorance.

I agree with Vincent's initial suggestion, i.e. mentioning its origins, at most.

**Comment by cjdelisle** [comment]
Thanks for your responses, @evalica your points are very pertinent and we will discuss them internally, thank you for raising them. What's important though is if this is a **problem**, please clearly state it and we will do something about it, we have to.

**Comment by cjdelisle** [comment]
After a conversation inside of XWiki Labs team and we determined that we will start using two distinct types of badges, one are for our prototypes which are not currently in active development and the others are for projects which we generally maintain/release. In the future we might consider handing over projects with a stipulation that it contains a "Donated by XWiki Labs" badge but we don't think it makes sense to apply this rule retroactively to projects which have become community projects (Including totem application).

**Comment by vmassol** [comment]
ok, thanks. One mention: all projects on xwiki-contrib are community project, do we agree? (since that's the point of xwiki-contrib: http://contrib.xwiki.org/xwiki/bin/view/Main/WebHome#HWhyjoinXWikiContrib).

**Comment by cjdelisle** [comment]
Ok by "community projects" I meant projects which are primarily maintained and released by people outside of labs, in the case of Realtime extension, it's hosted here but it's still maintained mostly by us.
I think "who releases it" is a fair test, how about you?

**Comment by vmassol** [comment]
For me the definition is that of http://contrib.xwiki.org/xwiki/bin/view/Main/WebHome#HWhyjoinXWikiContrib

i.e. as soon as you put a project on xwiki-contrib it's a community project, i.e. anyone is free to work on it and it should be handled as such. Otherwise, the project should not be moved on xwiki-contrib IMO (can be kept in one's own github project if it's not to be shared).

Now, as I've said before, I find it ok to mention who started the project. But then it would be also fair to mention in the same location the sum of all people who participated to it after the initial contribution.

WDYT?

**Pull request merged**
